In [2]:
import numpy as np #https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [6]:
#1.Podstawowe operacje na tablicach.
#(a) Wygeneruj macierz 3 × 3 z elementami od 0 do 8.
#[[0 1 2]
#[3 4 5]
#[6 7 8]]
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#2.Wygeneruj macierz 10 × 10 z losowymi warto´sciami i znajd ´z warto´s´c najmniejsz ˛a oraz najwi ˛eksz ˛

In [25]:
np_rand = np.random.rand(10,10)
np_rand

array([[0.84319985, 0.76845084, 0.28730661, 0.88997647, 0.880106  ,
        0.27191924, 0.47003352, 0.92936481, 0.82681017, 0.47305713],
       [0.3047047 , 0.72386038, 0.27201925, 0.71219093, 0.63242744,
        0.30492681, 0.21689232, 0.69215848, 0.84860639, 0.04066502],
       [0.81252092, 0.04954939, 0.26458603, 0.46103727, 0.65564635,
        0.96836036, 0.79387254, 0.56945531, 0.06935744, 0.57872592],
       [0.78142752, 0.81142495, 0.29790219, 0.16588287, 0.72287585,
        0.30357358, 0.77834594, 0.90315157, 0.64436736, 0.79911357],
       [0.745082  , 0.08113221, 0.49970911, 0.38156547, 0.2357098 ,
        0.78254883, 0.8336512 , 0.32069103, 0.09968273, 0.7371804 ],
       [0.63115522, 0.01790917, 0.10855995, 0.3270121 , 0.32673929,
        0.78219442, 0.32564625, 0.4819626 , 0.89969856, 0.43379423],
       [0.89026783, 0.60540457, 0.35222886, 0.52675533, 0.26736811,
        0.92787625, 0.37872237, 0.88970445, 0.20072022, 0.11181681],
       [0.03543868, 0.11753716, 0.2369630

In [26]:
np.amax(np_rand)

0.9960725976526024

In [27]:
np.amin(np_rand)

0.017909171969494486

In [43]:
#3. Wygeneruj macierz 5 × 5 z jedynkami na kraw ˛edziach i zerami w ´srodku.

In [42]:
np_ar = np.ones((5,5))
np_ar[1,1]=0
np_ar[1,2]=0
np_ar[1,3]=0
np_ar[2,1]=0
np_ar[2,2]=0
np_ar[2,3]=0
np_ar[3,1]=0
np_ar[3,2]=0
np_ar[3,3]=0
np_ar

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
#4. Create a 3×3 numpy array of all True’s

In [50]:
np.ones(shape=(3,3),dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [457]:
#5. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##> array([1, 3, 5, 7, 9])

In [458]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [59]:
#6.Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [63]:
arr[arr%2!=0]= -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [64]:
#6. Replace all odd numbers in arr with -1 without changing arr

In [128]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr%2!=0, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [75]:
#7. Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
arr.reshape(2,5) #instead of 5 it's better to use -1, num of cols is automatic then

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
#8. Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [82]:
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [90]:
np.vstack([a,b]) #hstack exists

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [91]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [93]:
#9. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [94]:
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [95]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [96]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [100]:
#10.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1,2,3])
##> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [105]:
np.hstack([np.vstack([a,a,a]).transpose().ravel(),a,a,a])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [106]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [107]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [108]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [110]:
#11. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [113]:
set(a[np.isin(a,b)])

{2, 4}

In [116]:
#np.setdiff1d(a,b)

In [118]:
np.intersect1d(a,b)

array([2, 4])

In [120]:
#12. From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [121]:
set(a[~np.isin(a,b)])

{1, 2, 3, 4}

In [124]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [133]:
#13. Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [134]:
np.where(a==b)

(array([1, 3, 5, 7]),)

In [140]:
#14. Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [149]:
a[(a >= 5) & (a<=10)]

array([ 6,  9, 10])

In [157]:
a[np.where((a>=5)&(a<=10))]

array([ 6,  9, 10])

In [159]:
a[np.where(np.logical_and(a>=5,a<=10))]

array([ 6,  9, 10])

In [165]:
#15. Convert the function maxx that works on two scalars, to work on two arrays.
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [168]:
maxx_vect = np.vectorize(maxx,otypes=[float])
maxx_vect(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [172]:
#16.Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [173]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [178]:
#17. Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [182]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [185]:
#19. Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [191]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [194]:
#20. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [199]:
matrix = np.random.uniform(5,10,(5,3))
matrix

array([[8.78612074, 7.3537223 , 5.42280662],
       [7.60273863, 5.57594604, 8.45178828],
       [6.02821741, 9.57841269, 7.42509406],
       [9.54897076, 9.83253087, 7.75387366],
       [7.94240486, 5.99261454, 5.39361866]])

In [206]:
np.random.randint(5,10,(5,3)) + np.random.rand(5,3)

array([[7.31814353, 7.67155645, 7.02921737],
       [7.5980636 , 9.96838123, 9.01954548],
       [9.16536793, 9.97676655, 6.58995836],
       [5.61883387, 5.11165323, 5.14380217],
       [6.96539468, 9.20001471, 8.32490303]])

In [208]:
#21. Print or show only 3 decimal places of the numpy array rand_arr.
rand_arr = np.random.random((5,3))

In [214]:
np.set_printoptions(precision=3)
rand_arr

array([[0.029, 0.657, 0.954],
       [0.222, 0.115, 0.341],
       [0.753, 0.633, 0.043],
       [0.123, 0.459, 0.749],
       [0.055, 0.656, 0.964]])

In [224]:
#22. Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

In [227]:
np.set_printoptions(suppress=True, precision=8)
rand_arr

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

In [250]:
#23. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)

In [233]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [234]:
#24. Print the full numpy array a without truncating.

In [255]:
np.set_printoptions(threshold=np.inf)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [256]:
#25. Import the iris dataset keeping the text intact.

In [263]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_data = np.genfromtxt(url, delimiter = ',', dtype = 'object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [264]:
iris_data

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

In [311]:
#26. Extract the text column species from the 1D iris imported in previous question.
import warnings 
warnings.filterwarnings('ignore')
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

In [318]:
iris_1d_arr = np.array([row[4] for row in iris_1d])
iris_1d_arr

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

In [313]:
#27. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
import warnings 
warnings.filterwarnings('ignore')
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.genfromtxt(url, delimiter=',', dtype=None, usecols = [0,1,2,3])

In [346]:
iris_2d_arr = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d_arr

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [355]:
#28. Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [387]:
first = np.genfromtxt(url, delimiter=',', dtype='float', usecols =[0])
np.mean(first)
np.std(first)
#np.median(first)

0.8253012917851409

In [382]:
np.mean(np.array(iris[:,0],dtype="float"))

5.843333333333334

In [383]:
np.std(np.array(iris[:,0],dtype="float"))

0.8253012917851409

In [384]:
np.median(np.array(iris[:,0],dtype="float"))

5.8

In [388]:
#29. Create a normalized form of iris's sepallength 
#whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [400]:
sepallength_normal = (sepallength - sepallength.min())/(sepallength.max()-sepallength.min())
sepallength_normal

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

In [401]:
sepallength_normal_v2 = (sepallength-np.amin(sepallength))/np.ptp(sepallength)
sepallength_normal_v2

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

In [403]:
#30. Compute the softmax score of sepallength.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [432]:
softmax = np.exp(sepallength)/np.sum(np.exp(sepallength))
softmax

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

In [431]:
def softmaxf(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x)) # I think it's wrong
    return e_x / e_x.sum(axis=0)

In [435]:
#31. Find the 5th and 95th percentile of iris's sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [437]:
np.percentile(sepallength,[5,95])

array([4.6  , 7.255])

In [466]:
#32.Insert np.nan values at 20 random positions in iris_2d dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [470]:
iris_2d[np.random.randint(0,150, size=20),np.random.randint(0,5, size=20)] = np.nan
iris_2d

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', nan],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', nan, b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', nan, b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [nan, b'3.9', b'1.3', nan, b'Iris-setosa'],
       [b'5.1', nan, b'1.4', b'0.3', b'Iris-setosa'],


In [472]:
#33. Find the number and position of missing values in iris_2d's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [478]:
np.isnan(iris_2d[:,0]).sum()

7

In [479]:
np.where(np.isnan(iris_2d[:,0]))

(array([ 26,  35,  65,  68,  87,  99, 101]),)

In [484]:
#34. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth')

In [491]:
iris_2d[np.logical_and(iris_2d[:,2]>1.5,iris_2d[:,0]<5.0)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [492]:
iris_2d[(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [497]:
#35. Select the rows of iris_2d that does not have any nan value.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [531]:
cond = [~np.any(np.isnan(row)) for row in iris_2d]

In [532]:
iris_2d[cond]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3

In [534]:
#36. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [540]:
#zle -> np.correlate(iris[:, 0], iris[:,2])

array([3484.25])

In [542]:
np.corrcoef(iris[:, 0], iris[:,2])[0,1] #Return Pearson product-moment correlation coefficients.

0.8717541573048718

In [547]:
#37. Find out if iris_2d has any missing values.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [549]:
np.any(np.isnan(iris_2d))

True

In [550]:
np.isnan(iris_2d).any()

True

In [552]:
#38. Replace all ccurrences of nan with 0 in numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [556]:
iris_2d[np.isnan(iris_2d)] = 0

In [557]:
iris_2d

array([[5.1, 3.5, 0. , 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0. ],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0. ],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 0. , 1.4, 0.2],
       [4.9, 3

In [559]:
#39. Find the unique values and the count of unique values in iris's species
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [563]:
np.unique(iris[:,4])

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object)

In [564]:
set(iris[:,4])

{b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'}

In [595]:
#40. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [586]:
iris_2 = np.genfromtxt(url, delimiter=',', dtype='str', usecols = [2])
iris[:, 2] = ['Petal length is: ' + iris_2[row] for row in range(0,len(iris))]

In [596]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:, 2] = ['Petal length is: ' + str(iris[row, 2]) for row in range(0,len(iris))]
iris

In [ ]:
'''
Less than 3 --> 'small'
3-5 --> 'medium'
'>=5 --> 'large'
'''

In [600]:
classif = {1:"small", 2:"medium", 3:"large"}

In [633]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:, 2] = iris[:, 2].astype("float")
cond = np.digitize(iris[:, 2],[0,3,5,np.inf])
iris[:, 2] = [classif[cond[row]] for row in range(0,len(iris))]
iris

array([[b'5.1', b'3.5', 'small', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', 'small', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', 'small', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', 'small', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', 'small', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', 'small', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', 'small', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', 'small', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', 'small', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', 'small', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', 'small', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', 'small', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', 'small', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', 'small', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', 'small', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', 'small', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', 'small', b'0.4', b'Iris-setosa'],
       [b'5.1'

In [639]:
#41. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [666]:
import math
iris_2d[:, 2]= iris_2d[:, 2].astype('float')
iris_2d[:, 0]= iris_2d[:, 0].astype("float")
volume = np.array([ (math.pi * iris_2d[i, 2] * math.pow(iris_2d[i, 0],2))/3 for i in range(0,len(iris))])
volume

array([ 38.13265163,  35.20049849,  30.07237208,  33.23805027,
        36.65191429,  51.91167701,  31.02218026,  39.26990817,
        28.38324243,  37.71481981,  45.80442089,  38.60389053,
        33.77840421,  21.29895099,  42.27327075,  51.03517266,
        39.69716477,  38.13265163,  57.83986235,  40.85641246,
        51.91167701,  40.85641246,  22.15870018,  46.30393412,
        45.84212   ,  41.88790205,  41.88790205,  42.47433268,
        39.6427105 ,  37.01215025,  38.60389053,  45.80442089,
        42.47433268,  44.34881629,  37.71481981,  31.41592654,
        41.1810437 ,  37.71481981,  26.35586797,  40.85641246,
        34.03392041,  27.56747554,  26.35586797,  41.88790205,
        51.75145578,  33.77840421,  43.58017329,  31.02218026,
        44.12366882,  36.65191429, 241.16959604, 193.01945264,
       244.29966952, 126.71090369, 203.52284408, 153.10551797,
       195.34737279,  82.97260357, 209.83325652, 110.43326496,
        91.62978573, 153.10237638, 150.79644737, 183.14

In [667]:
volume = volume[:, np.newaxis]
np.hstack([iris_2d,volume])

array([[5.1, b'3.5', 1.4, b'0.2', b'Iris-setosa', 38.13265162927291],
       [4.9, b'3.0', 1.4, b'0.2', b'Iris-setosa', 35.200498485922445],
       [4.7, b'3.2', 1.3, b'0.2', b'Iris-setosa', 30.0723720777127],
       [4.6, b'3.1', 1.5, b'0.2', b'Iris-setosa', 33.238050274980004],
       [5.0, b'3.6', 1.4, b'0.2', b'Iris-setosa', 36.65191429188092],
       [5.4, b'3.9', 1.7, b'0.4', b'Iris-setosa', 51.911677007917746],
       [4.6, b'3.4', 1.4, b'0.3', b'Iris-setosa', 31.022180256648003],
       [5.0, b'3.4', 1.5, b'0.2', b'Iris-setosa', 39.269908169872416],
       [4.4, b'2.9', 1.4, b'0.2', b'Iris-setosa', 28.38324242763259],
       [4.9, b'3.1', 1.5, b'0.1', b'Iris-setosa', 37.714819806345474],
       [5.4, b'3.7', 1.5, b'0.2', b'Iris-setosa', 45.80442088933919],
       [4.8, b'3.4', 1.6, b'0.2', b'Iris-setosa', 38.60389052731138],
       [4.8, b'3.0', 1.4, b'0.1', b'Iris-setosa', 33.77840421139745],
       [4.3, b'3.0', 1.1, b'0.1', b'Iris-setosa', 21.298950993787603],
       [5.8, b

In [671]:
volume_2 = (np.pi * iris_2d[:, 2] * (iris_2d[:, 0]**2))/3
volume_2
volume_2 = volume_2[:, np.newaxis]
np.hstack([iris_2d,volume_2])

array([[5.1, b'3.5', 1.4, b'0.2', b'Iris-setosa', 38.13265162927291],
       [4.9, b'3.0', 1.4, b'0.2', b'Iris-setosa', 35.200498485922445],
       [4.7, b'3.2', 1.3, b'0.2', b'Iris-setosa', 30.0723720777127],
       [4.6, b'3.1', 1.5, b'0.2', b'Iris-setosa', 33.238050274980004],
       [5.0, b'3.6', 1.4, b'0.2', b'Iris-setosa', 36.65191429188092],
       [5.4, b'3.9', 1.7, b'0.4', b'Iris-setosa', 51.911677007917746],
       [4.6, b'3.4', 1.4, b'0.3', b'Iris-setosa', 31.022180256648003],
       [5.0, b'3.4', 1.5, b'0.2', b'Iris-setosa', 39.269908169872416],
       [4.4, b'2.9', 1.4, b'0.2', b'Iris-setosa', 28.38324242763259],
       [4.9, b'3.1', 1.5, b'0.1', b'Iris-setosa', 37.714819806345474],
       [5.4, b'3.7', 1.5, b'0.2', b'Iris-setosa', 45.80442088933919],
       [4.8, b'3.4', 1.6, b'0.2', b'Iris-setosa', 38.60389052731138],
       [4.8, b'3.0', 1.4, b'0.1', b'Iris-setosa', 33.77840421139745],
       [4.3, b'3.0', 1.1, b'0.1', b'Iris-setosa', 21.298950993787603],
       [5.8, b

In [3]:
#42. Randomly sample iris's species such that setose is twice the number of versicolor and virginica
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [13]:
np.random.choice(np.unique(iris[:,4]),150,p=[0.5,0.25,0.25])

array([b'Iris-virginica', b'Iris-versicolor', b'Iris-setosa',
       b'Iris-setosa', b'Iris-virginica', b'Iris-setosa', b'Iris-setosa',
       b'Iris-virginica', b'Iris-virginica', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-versicolor', b'Iris-setosa', b'Iris-setosa',
       b'Iris-virginica', b'Iris-versicolor', b'Iris-virginica',
       b'Iris-setosa', b'Iris-versicolor', b'Iris-setosa', b'Iris-setosa',
       b'Iris-virginica', b'Iris-setosa', b'Iris-setosa',
       b'Iris-virginica', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-setosa', b'Iris-setosa', b'Iris-virginica', b'Iris-setosa',
       b'Iris-versicolor', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-virginica', b'Iris-virginica',
       b'Iris-setosa', b'Iris-virginica', b'Iris-setosa', b'Iris-setosa',
       b'Iris-virginica', b'Iris-virginica', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iri

In [1168]:
probs = np.r_[np.linspace(0,0.500,50), np.linspace(0.501,0.750,50), np.linspace(0.751,1.,50)]
indexes = np.searchsorted(probs, np.random.random(150))
iris[indexes]

array([[b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'6.0', b'2.2', b'4.0', b'1.0', b'Iris-versicolor'],
       [b'5.6', b'2.7', b'4.2', b'1.3', b'Iris-versicolor'],
       [b'6.7', b'3.3', b'5.7', b'2.1', b'Iris-virginica'],
       [b'6.7', b'3.3', b'5.7', b'2.1', b'Iris-virginica'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'6.4', b'3.2', b'4.5', b'1.5', b'Iris-versicolor'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.0', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'6.9', b'3.1', b'5.1', b'2.3', b'Iris-virginica'],
       [b'5.2', b'2.7', b'3.9', b'1.4', b'Iris-versicolor'],
       [b'6.3', b'2.3', b'4.4', b'1.3', b'Iris-versicolor'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'6.2', b'2.8', b'4.8', b'1.8', b'Iris-virginica'],
       [b'5.7', b'2.9', b'4.2', b'1.3', b'Iris-versicolo

In [27]:
#43. What is the value of second longest petallength of species setosa
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [34]:
np.unique(iris[:,4]) #b'Iris-setosa'

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object)

In [41]:
np.unique(sorted(iris[iris[:,4] == b'Iris-setosa', 2].astype('float')))[-2]

1.7

In [86]:
#44. Sort the iris dataset based on sepallength column.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [87]:
iris[np.argsort(iris[:,0])]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4

In [90]:
#iris = np.genfromtxt(url, delimiter=',', dtype='object', names = ('sepallength', \
#                                                                  'sepalwidth', 'petallength', 'petalwidth', 'species'))
#iris.sort(order=['sepallength','sepalwidth', 'petallength', 'petalwidth', 'species'])
#iris

In [92]:
#45. Find the most frequent value of petal length (3rd column) in iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [114]:
val = np.unique(iris[:,2], return_counts = True)[0]
cnt = np.unique(iris[:,2], return_counts = True)[1]

In [123]:
val[np.where(cnt == cnt.max())]

array([b'1.5'], dtype=object)

In [125]:
#46. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [1170]:
np.argwhere(iris[:,3].astype('float') > 1.0)[0]

array([50])

In [218]:
#47. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [227]:
np.where(a<10,10,(np.where(a>30,30,a)))

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [228]:
np.clip(a,10,30)

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [234]:
#48. Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [1171]:
a.argsort()[-5:]

array([7, 4, 1, 5, 2])

In [247]:
#The k-th element will be in its final sorted position and \
#all smaller elements will be moved before it and all larger elements behind it. 
np.partition(a,kth=-5)[-5:]
#argspartition etc.

array([40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

In [290]:
#49.Compute the counts of unique values row-wise.
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [285]:
row, col = np.shape(arr)
for x in range(0,row):
    val = np.unique(arr[x],return_counts = True)[0]
    cnt = np.unique(arr[x],return_counts = True)[1]
    for j in range(0,col):
        for i in range(0,len(val)):
            if arr[x][j] == val[i]:
                arr[x][j] = cnt[i]

In [286]:
arr

array([[2, 2, 1, 2, 2, 1, 1, 2, 1, 2],
       [3, 3, 1, 1, 1, 1, 1, 1, 1, 3],
       [3, 3, 1, 2, 3, 3, 2, 1, 3, 3],
       [2, 2, 1, 2, 2, 2, 1, 2, 1, 1],
       [2, 2, 1, 1, 2, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 1, 2, 1, 2, 1, 1]])

In [288]:
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

# Print
counts_of_all_values_rowwise(arr) #zle, nie odzwiercietla poprawnych miejsc

[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [312]:
#50. Convert array_of_arrays into a flat linear 1d array.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [315]:
np.hstack([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [317]:
np.concatenate([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [318]:
np.array([element for array in array_of_arrays for element in array])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [321]:
#51. Compute the one-hot encodings (dummy binary variables for each unique value in the array)
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

array([2, 3, 2, 2, 2, 1])

In [372]:
#52. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [437]:
[cnt for sp in np.unique(species_small) for cnt, spiecies in enumerate(species_small[species_small==sp])]

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8]

In [439]:
#53. Create group ids based on a given categorical variable. Use the following sample from iris species as input.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [457]:
[cnt for cnt, sp in enumerate(np.unique(species_small)) for i in species_small[species_small==sp]]

[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [458]:
#54. Create the ranks for the given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)

[ 9  4 15  0 17 16 17  8  9  0]


In [507]:
a.argsort().argsort()

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

In [505]:
#[4 2 6 0 8 7 9 3 5 1]

In [533]:
#55. Create a rank array of the same shape as a given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [540]:
a.ravel()

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [546]:
a.ravel().argsort()

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

In [561]:
np.vstack([a.ravel().argsort().argsort()[:5], a.ravel().argsort().argsort()[5:]])

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

In [563]:
a.shape

(2, 5)

In [562]:
a.ravel().argsort().argsort().reshape(a.shape)

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

In [565]:
#56. Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [571]:
max_a = [row.max() for row in a]
max_a

[9, 8, 6, 3, 9]

In [572]:
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

In [573]:
np.apply_along_axis(np.max, arr=a, axis=1)

array([9, 8, 6, 3, 9])

In [575]:
#57. Compute the min-by-max for each row for given 2d numpy array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [583]:
np.apply_along_axis(lambda a: np.min(a)/np.max(a), arr=a, axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [588]:
def min_by_max(a):
    return np.min(a)/np.max(a)

In [590]:
np.apply_along_axis(min_by_max, arr=a, axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [592]:
#58. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. 
#First time occurrences should be False.
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#> [False  True False  True False False  True  True  True  True]

Array:  [0 0 3 0 2 4 2 2 2 2]


In [622]:
idx = np.unique(a, return_index=True)[1]
out_matrix = np.full(a.size, True)
out_matrix[idx] = False
out_matrix

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

In [644]:
#59. Find the mean of a numeric column (sepalwidth) grouped by a categorical column in a 2D numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [670]:
[(iris[row,4],np.mean(iris[row:row+50,1].astype(float))) for row in range(0,150,50)]

[(b'Iris-setosa', 3.418),
 (b'Iris-versicolor', 2.7700000000000005),
 (b'Iris-virginica', 2.974)]

In [677]:
num_col = iris[:,1].astype('float')
grp_col = iris[:,4].astype("str")

In [681]:
[[grp_row, num_col[grp_col==grp_row].mean()] for grp_row in np.unique(grp_col)]

[['Iris-setosa', 3.418],
 ['Iris-versicolor', 2.7700000000000005],
 ['Iris-virginica', 2.974]]

In [698]:
#60. Import the image from the following URL and convert it to a numpy array
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [700]:
from io import BytesIO
from PIL import Image
import requests

get_url = requests.get(URL)
content = BytesIO(get_url.content)
img = Image.open(content)
#img.resize([200,200])
arr = np.asarray(img)

In [705]:
image = Image.fromarray(np.uint8(arr))
Image.Image.show(image)

In [707]:
#61. Drop all nan values from a 1D numpy array
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [710]:
arr[~np.isnan(arr)]

array([1., 2., 3., 5., 6., 7.])

In [735]:
#62. Compute the euclidean distance between two arrays a and b.
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
import math
suma = 0
math.pow(np.sum([np.math.pow(row[0]-row[1],2) for row in np.vstack([a,b]).transpose()]),0.5)

6.708203932499369

In [736]:
np.linalg.norm(a-b)

6.708203932499369

In [830]:
#63. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
b = np.array([8, 3, 7, 1, 2, 6, 0, 2])
#> array([2, 5])

In [835]:
for cnt, entry in enumerate(a):
    if cnt == 0:
        locl_max_idx = np.array([])
        maximum = entry
        max_idx = cnt
    else:
        if entry > maximum:
            maximum = entry
            max_idx = cnt
            #if cnt == a.shape[0]-1:
            #        locl_max_idx = np.append(locl_max_idx,max_idx)
        else:
            locl_max_idx = np.append(locl_max_idx,max_idx)
            maximum = a.min()
locl_max_idx

array([2., 5.])

In [842]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a))) # ten zewnetrzny np.diff nie jest potrzebny, wystarczy pozniej porownac -1
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5])

In [857]:
#64. Subtract the 1d array b_1d from the 2d array a_2d, such that
#each item of b_1d subtracts from respective row of a_2d.
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [855]:
a_2d - np.vstack([3*[b_1d[0]],3*[b_1d[1]],3*[b_1d[2]]])

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [877]:
a_2d - np.repeat(b_1d,3).reshape(3,3)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [868]:
a_2d - b_1d[:, None]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [883]:
a_2d - np.tile(b_1d,3).reshape(3,3).transpose()

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [886]:
#65. Find the index of 5th repetition of number 1 in x.
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [893]:
np.where(x==1)[0][4]

8

In [894]:
[i for i,j in enumerate(x) if j == 1][4]

8

In [896]:
#66. Convert numpy's datetime64 object to datetime's datetime object
# Input: a numpy datetime64 object
dt64 = np.datetime64('2018-02-25 22:10:10')

In [900]:
from datetime import datetime
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [901]:
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [911]:
#67. Compute the moving average of window size 3, for the given 1D array.
np.random.seed(100)
z = np.random.randint(10, size=10)
z

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

In [939]:
[z[i:i+3].mean() for i in range(0,len(z)-2)]

[6.333333333333333,
 6.0,
 5.666666666666667,
 4.666666666666667,
 3.6666666666666665,
 2.0,
 3.6666666666666665,
 3.0]

In [941]:
np.cumsum(z)

array([ 8, 16, 19, 26, 33, 33, 37, 39, 44, 46])

In [942]:
np.cumsum(z)[3:]

array([26, 33, 33, 37, 39, 44, 46])

In [943]:
np.cumsum(z)[:-3]

array([ 8, 16, 19, 26, 33, 33, 37])

In [948]:
#np.convolve(z, np.ones(3)/3, mode='valid')

In [952]:
#68. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers
l=10
sr=5
st=3

In [969]:
np.arange(sr,sr + st*l, st)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [971]:
#69. Given an array of a non-continuous sequence of dates. 
#Make it a continuous sequence of dates, by filling in the missing dates.

In [978]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)
#> ['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
#>  '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
#>  '2018-02-21' '2018-02-23']

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


In [1030]:
out_date = np.array([]).astype(np.datetime64)
for i, j in zip(dates,np.diff(dates)-1):
    out_date = np.append(out_date, i)
    out_date = np.append(out_date, i+j)
out_date = np.append(out_date, dates[-1])

In [1031]:
out_date

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

In [1038]:
#70. From the given 1d array arr, generate a 2d matrix using strides, 
#with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]
arr = np.arange(15) 
arr
#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [1141]:
def gen_2d_arr(length = 4, step = 2, array = arr):
    for idx, a in enumerate(arr):
        if idx == 0:
            arr_out = arr[idx:length]
        elif idx%step ==0:
            if arr[idx:idx+length].shape[0] == length:
                arr_out = np.vstack([arr_out,arr[idx:idx+length]])
    return arr_out

In [1152]:
gen_2d_arr()

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [1150]:
gen_2d_arr(4,1,arr)

array([[ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [1164]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])